name: Build C#

on:
  push:
    branches: [ "master", "v7-stable", "v7-latest", "v8/venus", "v8/saturn", "jdugan/add-actions" ]
  pull_request:
    branches: [ "master", "v7-stable", "v7-latest", "v8/venus", "v8/saturn" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v4
#      with:
#        dotnet-version: 4.7.2
    - name: Restore dependencies
      working-directory: csharp
      run: dotnet restore
    - name: Build
      working-directory: csharp
      run: dotnet build --no-restore
    - name: Test
      working-directory: csharp
      run: dotnet test --no-build --verbosity normal
