name: Build C#

on:
  push:
    branches: [ "master", "v7-stable", "v7-latest", i"v8/saturn", "v8/saturn" ]
  pull_request:
    branches: [ "master", "v7-stable", "v7-latest", i"v8/saturn", "v8/saturn" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
