name: Build C#

on:
  push:
    branches: [ "master", "v7-stable", "v7-latest" ] 
  pull_request:
    branches: [ "master", "v7-stable", "v7-latest" ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: csharp
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
